[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyinit"
version = "0.1.0"
authors = [
  { name="Karim", email="daynews19@gmail.com" },
]
description = "A tool for creating and managing Python projects"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich",
    "tomli; python_version < '3.11'",
    "tomli-w",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pyinit = "pyinit.main:main"
